apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 3

  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: petclinic
          image: petclinic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: front-cm
            - secretRef:
                name: front-secrets
