applications:
  pet-clinic-real-app:
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/abdelrahman-shebl/Depi
      targetRevision: HEAD
      path: Task10/K8s
    destination:
      namespace: petclinic
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
