# Global domain
global:
  domain: shebl.com


grafana:
  enabled: true
  adminPassword: "admin"
  defaultDashboardsEnabled: true

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - shebl.com
    path: /grafana
    pathType: Prefix
    tls: []

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
    security:
      admin_user: admin

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - shebl.com
    paths:
      - /prometheus
    tls: []

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}

    # Increase retention if needed
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s

alertmanager:
  enabled: false

additionalServiceMonitors:
  - name: argocd
    namespaceSelector:
      matchNames:
        - argocd
    selector:
      matchLabels:
        app.kubernetes.io/part-of: argocd
    endpoints:
      - port: metrics
        interval: 30s
        path: /metrics
