configs:
  secret:
    argocdServerAdminPassword: "$2a$10$MVBkBkAxErFWaBpXA4Ltz.Kiwhcz0CkNmVZZgZPa/03JpykN50BVO"
  cm:
    url: http://shebl.com/argo
  # params:
  #   server.insecure: "true"
  #   server.basehref: /argo/
  #   server.rootpath: /argo/

global:
  domain: shebl.com

server:
  replicas: 1
  
  extraArgs:
    - --basehref=/argo/
    - --rootpath=/argo/

  service:
    type: ClusterIP

  ingress:
    enabled: true
    hosts:
      - host: argocd.example.com
        paths:
          - path: /argocd
            pathType: Prefix

  ingress:
    enabled: true
    hostname: shebl.com
    path: /argo
    pathType: Prefix
    tls: false

  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8083
      targetPort: 8083
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

repoServer:
  replicas: 1
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8084
      targetPort: 8084
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

controller:
  replicas: 1
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8082
      targetPort: 8082
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

dex:
  enabled: false