services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"  
      - "6000:6000"  
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data: