# tasks file for docker
- name: Ubuntu Installation
  when: ansible_facts.distribution == 'Ubuntu'
  block:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
    
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: 
        - "{{ first_packages }}"
      
    - name: Shell commands
      ansible.builtin.shell:
        cmd: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc
          usermod -aG docker $USER
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Installing docker packages 
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        - "{{ second_packages }}"

- name: CentOS Installation
  when: ansible_facts.distribution == 'CentOS'
  block:

    - name: Install DNF packages
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Shell commands
      ansible.builtin.shell:
        cmd: config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - "{{ second_packages }}"
      notify: systemctl enable

- name: Docker Run 
  block:
    - name: Make a directory for the Image
      ansible.builtin.file:
        path: /home/abdelrahman/Desktop/Image
        state: directory
        
    - name: Copy Petclinic Image
      ansible.builtin.copy:
        src: /home/abdelrahman/Desktop/DEPI/Submissions/Task9/petclinic.tar
        dest: /home/abdelrahman/Desktop/Image

    - name: Load Image into docker 
      ansible.builtin.shell:
        cmd: docker load -i /home/abdelrahman/Desktop/Image/petclinic.tar

    - name: Remove the docker file 
      ansible.builtin.file:
        path: /home/abdelrahman/Desktop/Image/petclinic.tar
        state: absent

    - name: Stop running containers to avoid conflicts
      ansible.builtin.docker_container:
        name: all
        state: absent

    - name: Run the Image
      ansible.builtin.shell:
        cmd: docker run -p 8080:8080 -d petclinic 