apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: petclinic
          image: shebl22/petclinic:8cd8bb2970b3a81523a5b64d92cb25b0430617fa
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 512Mi
              cpu: 100m 
            limits:
              memory: 256Mi
              cpu: 1Gi 
            

          envFrom:
            - configMapRef:
                name: front-cm
            - secretRef:
                name: front-secrets
