services:
  petclinic-app:
    image: petclinic
    
    ports:
      - 30

    depends_on:
      - db

    networks:
      - net 
    env_file:
      - config.env

  db:
    image: mysql:9.2
    ports:
      - 3306:3306

    healthcheck:
      test: ["CMD-SHELL", ",mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

    networks:
      - net
    volumes:
      - mysql:/var/lib/mysql

    env_file:
      - secrets.env



volumes:
  mysql:

networks:
  net:
    